<<<<<<< Updated upstream
# Generated by Django 6.0.5 on 2026-05-29 04:56
=======
# Generated by Django 6.0.5 on 2026-05-29 14:38
>>>>>>> Stashed changes

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

<<<<<<< Updated upstream
    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Poses",
            fields=[
                ("poses_id", models.AutoField(primary_key=True, serialize=False)),
                ("name_of_poses_generated", models.CharField(max_length=225)),
                ("is_predefined", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name="User",
            fields=[
                ("user_id", models.AutoField(primary_key=True, serialize=False)),
                ("first_name", models.CharField(max_length=225)),
                ("last_name", models.CharField(max_length=225)),
                ("user_name", models.CharField(max_length=225)),
                ("password", models.CharField(max_length=225)),
                ("email_address", models.CharField(max_length=225)),
                ("is_permitted", models.IntegerField()),
                ("created_at", models.DateTimeField(null=True)),
                ("updated_at", models.DateTimeField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name="Export",
            fields=[
                ("export_id", models.AutoField(primary_key=True, serialize=False)),
                ("created_at", models.DateTimeField(blank=True, null=True)),
                (
                    "export_fid",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="api.poses"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="PoseSelection",
            fields=[
                (
                    "pose_selection_id",
                    models.AutoField(primary_key=True, serialize=False),
                ),
                ("selected_at", models.DateTimeField(blank=True, null=True)),
                (
                    "pose_selection_fid",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="api.poses"
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="poses",
            name="poses_fid",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="api.user"
            ),
=======
    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PosePreset',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(help_text="Display name for the pose (e.g., 'Thumbs Up', 'Happy Expression')", max_length=100)),
                ('slug', models.SlugField(help_text="URL-safe unique identifier (e.g., 'thumbs-up', 'happy')", max_length=100, unique=True)),
                ('description', models.TextField(blank=True, default='', help_text='Detailed description of the pose')),
                ('is_expression', models.BooleanField(default=False, help_text='True if this is a facial expression; False if body pose')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Pose Preset',
                'verbose_name_plural': 'Pose Presets',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Poses',
            fields=[
                ('poses_id', models.AutoField(primary_key=True, serialize=False)),
                ('name_of_poses_generated', models.CharField(max_length=225)),
                ('is_predefined', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='PuppetPart',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(help_text="Display name for the puppet part (e.g., 'Round Head', 'Left Arm')", max_length=100)),
                ('asset_url', models.CharField(help_text='URL or file path to the asset image/SVG', max_length=500)),
                ('part_type', models.CharField(choices=[('HEAD', 'Head'), ('TORSO', 'Torso'), ('LIMB', 'Limb'), ('FACE', 'Face Element'), ('EXTRA', 'Extra')], help_text='Category of puppet part', max_length=10)),
                ('description', models.TextField(blank=True, default='', help_text='Optional description for documentation')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Puppet Part',
                'verbose_name_plural': 'Puppet Parts',
                'ordering': ['part_type', 'name'],
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('user_id', models.AutoField(primary_key=True, serialize=False)),
                ('first_name', models.CharField(max_length=225)),
                ('last_name', models.CharField(max_length=225)),
                ('user_name', models.CharField(max_length=225)),
                ('password', models.CharField(max_length=225)),
                ('email_address', models.CharField(max_length=225)),
                ('is_permitted', models.IntegerField()),
                ('created_at', models.DateTimeField(null=True)),
                ('updated_at', models.DateTimeField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Export',
            fields=[
                ('export_id', models.AutoField(primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(blank=True, null=True)),
                ('export_fid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.poses')),
            ],
        ),
        migrations.CreateModel(
            name='PoseSelection',
            fields=[
                ('pose_selection_id', models.AutoField(primary_key=True, serialize=False)),
                ('selected_at', models.DateTimeField(blank=True, null=True)),
                ('pose_selection_fid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.poses')),
            ],
        ),
        migrations.AddField(
            model_name='poses',
            name='poses_fid',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.user'),
        ),
        migrations.CreateModel(
            name='PartConfiguration',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('position_x', models.FloatField(default=0.0, help_text='X coordinate position (pixels or normalized units)')),
                ('position_y', models.FloatField(default=0.0, help_text='Y coordinate position (pixels or normalized units)')),
                ('rotation', models.FloatField(default=0.0, help_text='Rotation angle in degrees (0-360)')),
                ('z_index', models.IntegerField(default=0, help_text='Layer ordering (higher values appear on top)')),
                ('scale', models.FloatField(default=1.0, help_text='Scale multiplier for the part (e.g., 1.0 = 100%)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('pose_preset', models.ForeignKey(help_text='Reference to the pose preset', on_delete=django.db.models.deletion.CASCADE, related_name='part_configurations', to='api.posepreset')),
                ('puppet_part', models.ForeignKey(help_text='Reference to the puppet part asset', on_delete=django.db.models.deletion.CASCADE, related_name='configurations', to='api.puppetpart')),
            ],
            options={
                'verbose_name': 'Part Configuration',
                'verbose_name_plural': 'Part Configurations',
                'ordering': ['z_index', 'puppet_part'],
                'unique_together': {('pose_preset', 'puppet_part')},
            },
>>>>>>> Stashed changes
        ),
    ]
