# Generated by Django 6.0.5 on 2026-05-29 04:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Poses",
            fields=[
                ("poses_id", models.AutoField(primary_key=True, serialize=False)),
                ("name_of_poses_generated", models.CharField(max_length=225)),
                ("is_predefined", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name="User",
            fields=[
                ("user_id", models.AutoField(primary_key=True, serialize=False)),
                ("first_name", models.CharField(max_length=225)),
                ("last_name", models.CharField(max_length=225)),
                ("user_name", models.CharField(max_length=225)),
                ("password", models.CharField(max_length=225)),
                ("email_address", models.CharField(max_length=225)),
                ("is_permitted", models.IntegerField()),
                ("created_at", models.DateTimeField(null=True)),
                ("updated_at", models.DateTimeField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name="Export",
            fields=[
                ("export_id", models.AutoField(primary_key=True, serialize=False)),
                ("created_at", models.DateTimeField(blank=True, null=True)),
                (
                    "export_fid",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="api.poses"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="PoseSelection",
            fields=[
                (
                    "pose_selection_id",
                    models.AutoField(primary_key=True, serialize=False),
                ),
                ("selected_at", models.DateTimeField(blank=True, null=True)),
                (
                    "pose_selection_fid",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="api.poses"
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="poses",
            name="poses_fid",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="api.user"
            ),
        ),
    ]
