# Generated by Django 6.0.5 on 2026-05-29 08:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="poses",
            name="is_predefined",
        ),
        migrations.AddField(
            model_name="poses",
            name="configuration",
            field=models.JSONField(default=list),
        ),
    ]
