# Generated by Django 6.0.5 on 2026-05-30 00:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_seed_dummy_data'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='puppetpart',
            options={'ordering': ['category', 'part_type', 'name'], 'verbose_name': 'Puppet Part', 'verbose_name_plural': 'Puppet Parts'},
        ),
        migrations.AddField(
            model_name='puppetpart',
            name='category',
            field=models.CharField(choices=[('HEAD', 'Head'), ('LIMBS', 'Limbs'), ('TORSO', 'Torso'), ('ACCESSORIES', 'Accessories')], default='HEAD', help_text='Main category of puppet part', max_length=20),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='puppetpart',
            name='part_type',
            field=models.CharField(choices=[('FACE', 'Face'), ('EYES', 'Eyes'), ('MOUTH', 'Mouth'), ('EARS', 'Ears'), ('HAIR', 'Hair'), ('EYEBROWS', 'Eyebrows'), ('LEFT_UPPER_ARM', 'Left Upper Arm'), ('RIGHT_UPPER_ARM', 'Right Upper Arm'), ('LEFT_FOREARM_HAND', 'Left Forearm & Hand'), ('RIGHT_FOREARM_HAND', 'Right Forearm & Hand'), ('LEFT_THIGH', 'Left Thigh'), ('RIGHT_THIGH', 'Right Thigh'), ('LEFT_LOWER_LEG_FOOT', 'Left Lower Leg & Foot'), ('RIGHT_LOWER_LEG_FOOT', 'Right Lower Leg & Foot'), ('TAIL', 'Tail'), ('TORSO_BODY', 'Torso'), ('WEARABLES', 'Wearables'), ('HOLDABLES', 'Holdables')], help_text='Specific type of puppet part', max_length=30),
        ),
    ]
