# Generated by Django 6.0.5 on 2026-05-30 06:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_restructure_puppetpart_hierarchy'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='puppetpart',
            new_name='api_puppetp_categor_c7f187_idx',
            old_name='api_puppet_p_categor_idx',
        ),
        migrations.AlterField(
            model_name='puppetpart',
            name='name',
            field=models.CharField(help_text="Display name for this specific option (e.g., 'Round Eyes', 'head-1')", max_length=100),
        ),
    ]
